'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace OilPricePTT
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.pttor.com", ConfigurationName:="OilPricePTT.OilPriceSoap")>  _
    Public Interface OilPriceSoap
        
        'CODEGEN: Generating message contract since element name Language from namespace http://www.pttor.com is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pttor.com/CurrentOilPrice", ReplyAction:="*")>  _
        Function CurrentOilPrice(ByVal request As OilPricePTT.CurrentOilPriceRequest) As OilPricePTT.CurrentOilPriceResponse
        
        'CODEGEN: Generating message contract since element name Language from namespace http://www.pttor.com is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pttor.com/CurrentOilPriceProvincial", ReplyAction:="*")>  _
        Function CurrentOilPriceProvincial(ByVal request As OilPricePTT.CurrentOilPriceProvincialRequest) As OilPricePTT.CurrentOilPriceProvincialResponse
        
        'CODEGEN: Generating message contract since element name Language from namespace http://www.pttor.com is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pttor.com/GetOilPrice", ReplyAction:="*")>  _
        Function GetOilPrice(ByVal request As OilPricePTT.GetOilPriceRequest) As OilPricePTT.GetOilPriceResponse
        
        'CODEGEN: Generating message contract since element name Language from namespace http://www.pttor.com is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pttor.com/GetOilPriceProvincial", ReplyAction:="*")>  _
        Function GetOilPriceProvincial(ByVal request As OilPricePTT.GetOilPriceProvincialRequest) As OilPricePTT.GetOilPriceProvincialResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CurrentOilPriceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CurrentOilPrice", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.CurrentOilPriceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.CurrentOilPriceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class CurrentOilPriceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Language As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Language As String)
            MyBase.New
            Me.Language = Language
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CurrentOilPriceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CurrentOilPriceResponse", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.CurrentOilPriceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.CurrentOilPriceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class CurrentOilPriceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CurrentOilPriceResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CurrentOilPriceResult As String)
            MyBase.New
            Me.CurrentOilPriceResult = CurrentOilPriceResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CurrentOilPriceProvincialRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CurrentOilPriceProvincial", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.CurrentOilPriceProvincialRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.CurrentOilPriceProvincialRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class CurrentOilPriceProvincialRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Language As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Province As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Language As String, ByVal Province As String)
            MyBase.New
            Me.Language = Language
            Me.Province = Province
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CurrentOilPriceProvincialResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CurrentOilPriceProvincialResponse", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.CurrentOilPriceProvincialResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.CurrentOilPriceProvincialResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class CurrentOilPriceProvincialResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CurrentOilPriceProvincialResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CurrentOilPriceProvincialResult As String)
            MyBase.New
            Me.CurrentOilPriceProvincialResult = CurrentOilPriceProvincialResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOilPriceRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOilPrice", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.GetOilPriceRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.GetOilPriceRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class GetOilPriceRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Language As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public DD As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public MM As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public YYYY As Short
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Language As String, ByVal DD As Short, ByVal MM As Short, ByVal YYYY As Short)
            MyBase.New
            Me.Language = Language
            Me.DD = DD
            Me.MM = MM
            Me.YYYY = YYYY
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOilPriceResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOilPriceResponse", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.GetOilPriceResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.GetOilPriceResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class GetOilPriceResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetOilPriceResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetOilPriceResult As String)
            MyBase.New
            Me.GetOilPriceResult = GetOilPriceResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOilPriceProvincialRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOilPriceProvincial", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.GetOilPriceProvincialRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.GetOilPriceProvincialRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class GetOilPriceProvincialRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Language As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public DD As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public MM As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public YYYY As Short
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Province As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Language As String, ByVal DD As Short, ByVal MM As Short, ByVal YYYY As Short, ByVal Province As String)
            MyBase.New
            Me.Language = Language
            Me.DD = DD
            Me.MM = MM
            Me.YYYY = YYYY
            Me.Province = Province
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOilPriceProvincialResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetOilPriceProvincialResponse", [Namespace]:="http://www.pttor.com", Order:=0)>  _
        Public Body As OilPricePTT.GetOilPriceProvincialResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As OilPricePTT.GetOilPriceProvincialResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.pttor.com")>  _
    Partial Public Class GetOilPriceProvincialResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetOilPriceProvincialResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetOilPriceProvincialResult As String)
            MyBase.New
            Me.GetOilPriceProvincialResult = GetOilPriceProvincialResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface OilPriceSoapChannel
        Inherits OilPricePTT.OilPriceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OilPriceSoapClient
        Inherits System.ServiceModel.ClientBase(Of OilPricePTT.OilPriceSoap)
        Implements OilPricePTT.OilPriceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function OilPricePTT_OilPriceSoap_CurrentOilPrice(ByVal request As OilPricePTT.CurrentOilPriceRequest) As OilPricePTT.CurrentOilPriceResponse Implements OilPricePTT.OilPriceSoap.CurrentOilPrice
            Return MyBase.Channel.CurrentOilPrice(request)
        End Function
        
        Public Function CurrentOilPrice(ByVal Language As String) As String
            Dim inValue As OilPricePTT.CurrentOilPriceRequest = New OilPricePTT.CurrentOilPriceRequest()
            inValue.Body = New OilPricePTT.CurrentOilPriceRequestBody()
            inValue.Body.Language = Language
            Dim retVal As OilPricePTT.CurrentOilPriceResponse = CType(Me,OilPricePTT.OilPriceSoap).CurrentOilPrice(inValue)
            Return retVal.Body.CurrentOilPriceResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function OilPricePTT_OilPriceSoap_CurrentOilPriceProvincial(ByVal request As OilPricePTT.CurrentOilPriceProvincialRequest) As OilPricePTT.CurrentOilPriceProvincialResponse Implements OilPricePTT.OilPriceSoap.CurrentOilPriceProvincial
            Return MyBase.Channel.CurrentOilPriceProvincial(request)
        End Function
        
        Public Function CurrentOilPriceProvincial(ByVal Language As String, ByVal Province As String) As String
            Dim inValue As OilPricePTT.CurrentOilPriceProvincialRequest = New OilPricePTT.CurrentOilPriceProvincialRequest()
            inValue.Body = New OilPricePTT.CurrentOilPriceProvincialRequestBody()
            inValue.Body.Language = Language
            inValue.Body.Province = Province
            Dim retVal As OilPricePTT.CurrentOilPriceProvincialResponse = CType(Me,OilPricePTT.OilPriceSoap).CurrentOilPriceProvincial(inValue)
            Return retVal.Body.CurrentOilPriceProvincialResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function OilPricePTT_OilPriceSoap_GetOilPrice(ByVal request As OilPricePTT.GetOilPriceRequest) As OilPricePTT.GetOilPriceResponse Implements OilPricePTT.OilPriceSoap.GetOilPrice
            Return MyBase.Channel.GetOilPrice(request)
        End Function
        
        Public Function GetOilPrice(ByVal Language As String, ByVal DD As Short, ByVal MM As Short, ByVal YYYY As Short) As String
            Dim inValue As OilPricePTT.GetOilPriceRequest = New OilPricePTT.GetOilPriceRequest()
            inValue.Body = New OilPricePTT.GetOilPriceRequestBody()
            inValue.Body.Language = Language
            inValue.Body.DD = DD
            inValue.Body.MM = MM
            inValue.Body.YYYY = YYYY
            Dim retVal As OilPricePTT.GetOilPriceResponse = CType(Me,OilPricePTT.OilPriceSoap).GetOilPrice(inValue)
            Return retVal.Body.GetOilPriceResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function OilPricePTT_OilPriceSoap_GetOilPriceProvincial(ByVal request As OilPricePTT.GetOilPriceProvincialRequest) As OilPricePTT.GetOilPriceProvincialResponse Implements OilPricePTT.OilPriceSoap.GetOilPriceProvincial
            Return MyBase.Channel.GetOilPriceProvincial(request)
        End Function
        
        Public Function GetOilPriceProvincial(ByVal Language As String, ByVal DD As Short, ByVal MM As Short, ByVal YYYY As Short, ByVal Province As String) As String
            Dim inValue As OilPricePTT.GetOilPriceProvincialRequest = New OilPricePTT.GetOilPriceProvincialRequest()
            inValue.Body = New OilPricePTT.GetOilPriceProvincialRequestBody()
            inValue.Body.Language = Language
            inValue.Body.DD = DD
            inValue.Body.MM = MM
            inValue.Body.YYYY = YYYY
            inValue.Body.Province = Province
            Dim retVal As OilPricePTT.GetOilPriceProvincialResponse = CType(Me,OilPricePTT.OilPriceSoap).GetOilPriceProvincial(inValue)
            Return retVal.Body.GetOilPriceProvincialResult
        End Function
    End Class
End Namespace
